"""empty message

Revision ID: 735f6c93950e
Revises: 95e99768078f
Create Date: 2020-05-06 17:35:51.504754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735f6c93950e'
down_revision = '95e99768078f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'rate')
    # ### end Alembic commands ###
