"""empty message

Revision ID: 95e99768078f
Revises: 7f8357c1aa9c
Create Date: 2020-05-05 23:16:27.267918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95e99768078f'
down_revision = '7f8357c1aa9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('username', sa.String(length=140), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    op.drop_column('post', 'username')
    # ### end Alembic commands ###
